version: '3'

services:
  web:
    build: .
    command: python run.py
    environment:
      - DATABASE_URL=mysql+pymysql://incust:incust@db/incust
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: percona:8.0.23-14
    restart: always
    container_name: db
    environment:
      - MYSQL_DATABASE=incust
      - MYSQL_USER=incust
      - MYSQL_PASSWORD=incust
      - MYSQL_ROOT_PASSWORD=incust
    ports:
      - "8080:8080"
