swagger: "2.0"
info:
  title: Product lists API
  description: Test challenge for Incust
  version: "1.0.0"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /auth/login:
    post:
      operationId: "api.views.auth.login"
      summary: Login with username - password pair and obtain JWT Token
      responses:
        200:
          description: Access token
          schema:
            type: object
            properties:
              access_token:
                type: "string"
                description: JWT token

  /auth/signup:
    post:
      operationId: "api.views.auth.signup"
      summary: Login with username - password pair and obtain JWT Token
      responses:
        200:
          description: Access token
          schema:
            type: object
            properties:
              access_token:
                type: "string"
                description: JWT token

  /auth/profile:
    put:
      operationId: "api.views.auth.update"
      summary: Login with username - password pair and obtain JWT Token
      responses:
        200:
          description: Access token
          schema:
            type: object
            properties:
              access_token:
                type: "string"
                description: JWT token

  /product_lists:
    get:
      operationId: "api.views.product_lists.read_all"
      summary: Login with username - password pair and obtain JWT Token
      responses:
        200:
          description: Access token
          schema:
            type: object
            properties:
              access_token:
                type: "string"
                description: JWT token

    post:
      operationId: "api.views.product_lists.create"
      summary: Login with username - password pair and obtain JWT Token
      responses:
        200:
          description: Access token
          schema:
            type: object
            properties:
              access_token:
                type: "string"
                description: JWT token

  /product_lists/{list_id}:
    get:
      operationId: "api.views.product_lists.read_one"
      summary: Login with username - password pair and obtain JWT Token
      parameters:
        - name: list_id
          in: path
          description: ID of product list
          type: integer
          required: true
      responses:
        200:
          description: Access token
          schema:
            type: object
            properties:
              access_token:
                type: "string"
                description: JWT token
